# Welcome to Jekyll!
#
title: Trabalho Remoto
email: joepreludian+plataforma_apoio_ao_trabalho_remoto@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Forma de prover às empresas e profissionais liberais uma forma de 
  ser possibilitado o teletrabalho (Homeoffice) por meio de cartilha
  intuitiva.
baseurl: "/plataforma_apoio_ao_trabalho_remoto/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jjrt42
github_username:  cartilha_homeoffice

# Build settings
markdown: kramdown

# theme: just-the-docs
remote_theme: pmarsceill/just-the-docs

plugins:
  - jekyll-feed

aux_links:
  "Site no Github":
    - "//github.com/joepreludian/plataforma_apoio_ao_trabalho_remoto"

footer_content: "Projeto OpenSource. Licença sob Creative Commons Atribuição-NãoComercial-CompartilhaIgual CC BY-NC-SA"

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
