# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Suporte ao Homeoffice
email: suporteaohomeoffice@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Site com guia para ajuda para oferecer às empresas uma cartilha para
  ser possibilitado o teletrabalho (Homeoffice), por meio do oferecimento
  da indicação de serviços voltados a possibilitar o Homeoffice
baseurl: "/plataforma_apoio_ao_trabalho_remoto" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username:  cartilha_homeoffice

# Build settings
markdown: kramdown

theme: just-the-docs
remote_theme: pmarsceill/just-the-docs

plugins:
  - jekyll-feed

aux_links:
  "Just the Docs on GitHub":
    - "//github.com/pmarsceill/just-the-docs"

footer_content: "Projeto Opensource, distribuído sobre a Common License"
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
